services:
  cloudflaretunnel:
    image: cloudflare/cloudflared
    env_file: ./.env
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    networks:
      - keycloak_stack
    mem_limit: "15M"
    restart: unless-stopped

  wiki-nginx:
    image: nginx:latest
    container_name: wiki-nginx
    volumes:
      - ./wiki-nginx-config:/etc/nginx/conf.d
    networks:
      - keycloak_stack
    mem_limit: "15M"
    restart: unless-stopped

  wiki:
    image: requarks/wiki:2.5
    depends_on:
      - postgres
    environment:
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    # ports:
    #   - "80:3000"
    restart: unless-stopped
    networks:
      - keycloak_stack
    mem_limit: "100M"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outline", "-U", "user"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    restart: unless-stopped
    networks:
      - keycloak_stack
    mem_limit: "15M"
  
  # pgadmin:
  #   image: dpage/pgadmin4
  #   depends_on:
  #     - postgres
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
  #     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
  #   # ports:
  #   #   - "5050:80"
  #   restart: unless-stopped
  #   networks:
  #     - keycloak_stack


networks:
  keycloak_stack:
    external: true

