version: '3'

services:

  cloudflaretunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run

  finances-nginx:
    image: nginx:latest
    container_name: finances-nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./finances-nginx-config:/etc/nginx/conf.d   # Mount your custom Nginx configuration
      - ./logs:/var/log/nginx

  finances-app:
    image: fireflyiii/core:latest
    hostname: finances-app
    container_name: finances-app
    restart: always
    env_file: .env
    depends_on:
      - finances-db

  finances-db:
    image: mariadb
    hostname: finances-db
    container_name: finances-db
    env_file: .db.env
    volumes:
      - ./mysql:/var/lib/mysql

  finances-importer:
    image: fireflyiii/data-importer:latest
    hostname: finances-importer
    restart: always
    container_name: finances-importer
    env_file: .importer.env

  #
  # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace REPLACEME below
  # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
  #
  finances-cron:
    image: alpine
    container_name: finances-cron
    command: sh -c "echo \"0 3 * * * wget -qO- http://finances-app:8080/api/v1/cron/REPLACEME\" | crontab - && crond -f -L /dev/stdout"




