services:

  finances-app:
    image: fireflyiii/core:latest
    hostname: finances-app
    container_name: finances-app
    restart: unless-stopped
    env_file: .env
    depends_on:
      - finances-db
    ports:
      - 5600:8080

  finances-db:
    image: mariadb
    hostname: finances-db
    container_name: finances-db
    env_file: .db.env
    volumes:
      - ./mysql:/var/lib/mysql

  finances-importer:
    image: fireflyiii/data-importer:latest
    hostname: finances-importer
    restart: unless-stopped
    container_name: finances-importer
    env_file: .importer.env
    ports:
      - 5610:8080

  #
  # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace REPLACEME below
  # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
  #
  finances-cron:
    image: alpine
    container_name: finances-cron
    env_file: .env
    command: sh -c "echo \"0 3 * * * wget -qO- http://finances-app:8080/api/v1/cron/$STATIC_CRON_TOKEN\" | crontab - && crond -f -L /dev/stdout"
