services:
  coredns:
    image: coredns/coredns:latest
    container_name: coredns
    restart: unless-stopped
    ports:
      - "10.8.0.5:53:53/udp"
      - "10.8.0.5:53:53/tcp"
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 128M
    volumes:
      - ./config/010-Corefile:/Corefile:ro
    command: -conf /Corefile

  nginx-proxy:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    depends_on:
      - coredns
    ports:
      - "10.8.0.5:80:80"
      - "10.8.0.5:443:443"
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 128M
    volumes:
      - ./config/020-nginx.conf:/etc/nginx/nginx.conf:ro
