services:
  coredns:
    image: coredns/coredns:latest
    container_name: coredns
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config/010-Corefile:/Corefile:ro
    command: -conf /Corefile
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 128M

  nginx-proxy:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    depends_on:
      - coredns
    network_mode: host
    volumes:
      - ./config/020-nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 128M
