services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: ${DOMAIN}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      DISABLE_ADMIN_TOKEN: false
    volumes:
      - ./data/:/data/
    ports:
      - 5200:80
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 128M
