services:
  superproductivity:
    image: johannesjo/super-productivity:latest
    ports:
      - 5300:80
    environment:
      - WEBDAV_BACKEND=http://localhost:5400
      - WEBDAV_BASE_URL=http://localhost:5400/
      - WEBDAV_USERNAME=jkantiwal
      - WEBDAV_SYNC_FOLDER_PATH=/jkantiwal
      - SYNC_INTERVAL=1m
      - IS_COMPRESSION_ENABLED=true
      - IS_ENCRYPTION_ENABLED=false
    depends_on:
      - webdav

  # WebDAV backend server (Optional)
  #   Used with the WEBDAV_BACKEND environment variable
  webdav:
    image: hacdias/webdav:latest
    volumes:
      - ./webdav.yaml:/config.yml:ro
      - ./data:/data
    ports:
      - 5400:80