services:
  postgresk:
    image: docker.io/postgres
    volumes:
      # - /var/jk/docker/keycloak/data/postgresk:/var/lib/postgresql/data
      - ./data/postgresk:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Europe/Berlin
    mem_limit: "100M"
    restart: unless-stopped

  keycloak:
    image: keycloak/keycloak:26.0
    container_name: keycloak
    ports:
      - "6000:8080"
    expose: 
      - "8080"
    command: start --hostname https://keycloak.jcloud.v6.navy --proxy-headers xforwarded --spi-login-protocol-openid-connect-suppress-logout-confirmation-screen=true --tls-hostname-verifier ANY
    environment:
      TZ: Europe/Berlin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgresk:5432/keycloak
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_PROXY: edge
      KC_HTTP_ENABLED: true
      JAVA_OPTS: >
        -Xms512m -Xmx768m
        -XX:MetaspaceSize=128m
        -XX:MaxMetaspaceSize=256m
        -XX:+UseParallelGC
        -XX:+OptimizeStringConcat
    # mem_limit: "300M"
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 1G
    depends_on:
      - postgresk
    restart: unless-stopped

# ## proxy_net network is created by ansible
# networks:
#   proxy_net:
#     external: true
# http://pm01.jk:6000