services:

  # cloudflaretunnel:
  #   image: cloudflare/cloudflared:2023.2.1
  #   restart: unless-stopped
  #   environment:
  #     - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
  #   command: tunnel --no-autoupdate run

  # nextcloud-nginx:
  #   image: nginx:latest
  #   container_name: nextcloud-nginx
  #   depends_on:
  #     - nextcloud
  #   volumes:
  #     # - ./nextcloud-nginx-config:/etc/nginx/conf.d   # Mount your custom Nginx configuration
  #     - ./config/nextcloud.nginx.conf:/etc/nginx/conf.d/default.conf


  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --innodb_read_only_compressed=OFF
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/mysql:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 128M
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_INITDB_SKIP_TZINFO=1
      - MARIADB_AUTO_UPGRADE=1

  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M
    hostname: nextcloud-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    ports:
      - 5500:80
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 2048M
    environment:
      # only for first time creating the container, the we must comment these two lines
      # NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      # NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}

      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: nextcloud-db

      REDIS_HOST: nextcloud-redis
      REDIS_HOST_PASSWORD: ${REDIS_PASSWORD}

      NEXTCLOUD_DATA_DIR: /var/www/html/data
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_TRUSTED_DOMAINS}
      NEXTCLOUD_UPDATE: 1
      NEXTCLOUD_INIT_HTACCESS: true
      SKIP_DOMAIN_VALIDATION: 'true'

      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
      PHP_UPLOAD_LIMIT: ${PHP_UPLOAD_LIMIT}
      APACHE_BODY_LIMIT: ${APACHE_BODY_LIMIT}
      APACHE_SERVERNAME: nextcloud.kantiwal.xyz
      NEXTCLOUD_SKIP_INSTALL: true
    volumes:
      - ./data/nextcloud:/var/www/html/data
      - ./data/nextcloud-config:/var/www/html/config
