version: '3'

services:

  cloudflaretunnel:
    container_name: cloudflaretunnel-demo-1
    image: cloudflare/cloudflared:2023.2.1
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=eyJhIjoiMDZjMDM5MWI0NjYxOWRlMGJkZDEyYjlmYjUxMjc0YTUiLCJ0IjoiNzgwYzJhNTMtZjg1OC00MThkLWIzYmEtMmRlNDIwMGJhYzNlIiwicyI6Ik1UTXlaalEzT1RVdFl6ZzJPQzAwWm1FekxUazFZakV0TkRnek5qUTFORE0zTTJRNCJ9
    command: tunnel --no-autoupdate run

  nextcloud-nginx:
    image: nginx:latest
    container_name: nextcloud-nginx
    restart: always
    volumes:
      - ./nextcloud-nginx-config:/etc/nginx/conf.d   # Mount your custom Nginx configuration

  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --innodb_read_only_compressed=OFF
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test #SQL root Passwort eingeben
      - MYSQL_PASSWORD=test #SQL Benutzer Passwort eingeben
      - MYSQL_DATABASE=nextcloud #Datenbank Name
      - MYSQL_USER=nextcloud #SQL Nutzername
      - MYSQL_INITDB_SKIP_TZINFO=1
      - MARIADB_AUTO_UPGRADE=1
  
  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    hostname: nextcloud-redis
    restart: unless-stopped
    command: redis-server --requirepass test # Redis Passwort eingeben

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    environment:
        REDIS_HOST: nextcloud-redis
        REDIS_HOST_PASSWORD: test # Redis Passwort von oben wieder eingeben
    volumes:
      - ./app:/var/www/html
      - ./daten:/var/www/html/data
