services:
  cloudflaretunnel-gitlab:
    image: cloudflare/cloudflared
    env_file: ./.env
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN_GITLAB}
    command: tunnel --no-autoupdate run
    restart: unless-stopped

  gitlab-nginx:
    image: nginx:latest
    container_name: gitlab-nginx
    volumes:
      - ./gitlab-nginx-config:/etc/nginx/conf.d
    restart: unless-stopped


  # cloudflaretunnel-gitlab-ssh:
  #   image: cloudflare/cloudflared
  #   env_file: ./.env
  #   environment:
  #     - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN_GITLAB_SSH}
  #   command: tunnel --no-autoupdate run
  #   restart: unless-stopped


  gitlab:
    image: gitlab/gitlab-ce
    hostname: 'gitlab.kantiwal.xyz'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.kantiwal.xyz'
    # gitlab_rails['gitlab_shell_ssh_port'] = 22
    # gitlab_rails['gitlab_ssh_host'] = 'gitlab-ssh.kantiwal.xyz'
    # ports:
    #   - '3000:3000'
    # - '2424:22'
    # - '8929:8929'
    # - '443:443'
    # deploy:
    #   resources:
    #     limits:
    #       memory: 6000M
    volumes:
      - ./data/gitlab/config:/etc/gitlab
      - ./data/gitlab/logs:/var/log/gitlab
      - ./data/gitlab/data:/var/opt/gitlab
    shm_size: '256m'

  # gitlab-ssh:
  #   build:
  #     context: ./gitlab-ssh
  #     dockerfile: Dockerfile
  #   # ports:
  #   #   - "2424:2424"
  #   restart: unless-stopped

  gitlab-runner:
    image: gitlab/gitlab-runner
    deploy:
      resources:
        limits:
          memory: 2500M
    volumes:
      - ./data/gitlab-runner/config/config.toml:/etc/gitlab-runner/config.toml
      - ./ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gitlab
