version: '3'

services:

  cloudflaretunnel:
    image: cloudflare/cloudflared
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
  
  wordpress:
    image: wordpress
    container_name: portfolio
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./app:/var/www/html

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql

  portfolio-nginx:
    image: nginx:latest
    container_name: portfolio-nginx
    volumes:
      - ./portfolio-nginx-config:/etc/nginx/conf.d
