---
- name: Create backup archive on remote
  ansible.builtin.command: >
    zip -r -P "{{ wireguard_backup_password }}"
    /tmp/wireguard_backup_{{ ansible_date_time.epoch }}.zip
    /etc/wireguard /opt/WGDashboard
  register: backup_result

- name: Show backup result
  debug:
    var: backup_result.stdout_lines

- name: Fetch backup to role files dir
  ansible.builtin.fetch:
    src: "/tmp/wireguard_backup_{{ ansible_date_time.epoch }}.zip"
    dest: "{{ role_path }}/files/"
    flat: true

- name: Remove backup from remote
  ansible.builtin.file:
    path: "/tmp/wireguard_backup_{{ ansible_date_time.epoch }}.zip"
    state: absent
