---
- name: Ensure required directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /etc/coredns

- name: Deploy CoreDNS Corefile from template
  ansible.builtin.template:
    src: coredns.Corefile.j2
    dest: /etc/coredns/Corefile
    owner: root
    group: root
    mode: '0644'

- name: Pull CoreDNS Docker image
  community.docker.docker_image:
    name: coredns/coredns
    tag: latest
    source: pull

- name: Run CoreDNS container on host network
  community.docker.docker_container:
    name: coredns
    image: coredns/coredns:latest
    state: started
    restart_policy: unless-stopped
    network_mode: host
    volumes:
      - "/etc/coredns:/etc/coredns"
    command:
      - "-conf"
      - "/etc/coredns/Corefile"
    recreate: true
