---
# roles/wg-server/tasks/setup-ca.yml

- name: Ensure certificate directories exist
  ansible.builtin.file:
    path: "{{ role_path }}/certs/{{ item }}"
    state: directory
    mode: '0700'
  loop:
    - ca
    - services
  delegate_to: localhost

# Generate internal CA key
- name: Generate private key for internal CA
  community.crypto.openssl_privatekey:
    path: "{{ role_path }}/certs/ca/ca.key"
    size: 4096
    type: RSA
    state: present
  delegate_to: localhost

# Generate self-signed CA certificate
- name: Generate self-signed CA certificate
  community.crypto.x509_certificate:
    path: "{{ role_path }}/certs/ca/ca.crt"
    privatekey_path: "{{ role_path }}/certs/ca/ca.key"
    provider: selfsigned
    state: present
  delegate_to: localhost

# Generate private key for each internal service
- name: Generate private key for each service
  community.crypto.openssl_privatekey:
    path: "{{ role_path }}/certs/services/{{ item }}.key"
    size: 2048
    type: RSA
    state: present
  loop: "{{ cert_hosts }}"
  loop_control:
    label: "{{ item }}"
  delegate_to: localhost

- name: Create CSR for each internal service
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ role_path }}/certs/services/{{ item }}.key"
    common_name: "{{ item }}"
    organization_name: Internal
    subject_alt_name:
      - "DNS:{{ item }}"
  loop: "{{ cert_hosts }}"
  loop_control:
    label: "{{ item }}"
  register: csr_results
  delegate_to: localhost

- name: Create self-signed certificate from CSR for each internal service
  community.crypto.x509_certificate:
    path: "{{ role_path }}/certs/services/{{ item.item }}.crt"
    csr_content: "{{ item.csr }}"
    privatekey_path: "{{ role_path }}/certs/services/{{ item.item }}.key"
    provider: selfsigned
    state: present
  loop: "{{ csr_results.results }}"
  loop_control:
    label: "{{ item.item }}"
  delegate_to: localhost

- name: Show generated certificates
  ansible.builtin.debug:
    msg: "Generated {{ item }} certificate: {{ role_path }}/certs/services/{{ item }}.crt"
  loop: "{{ cert_hosts }}"
  loop_control:
    label: "{{ item }}"
  delegate_to: localhost
